name: Probando Workflow

on:
  push:
    branches: [ "main" ]

jobs:
  run-time-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: probando script workflows
        run: |
          echo "Hola GitHub y hola mundo por aca sebastian vargas"
